name: Documentation

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'

    - name: Install dependencies
      run: |
        npm install
        npm install -g typedoc@0.20.37 typescript
    - name: Build documentation
      run: python docs/build.py

    - name: Deploy to GitHub pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: docs/_build
        committer_name: github-actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
