# This is a basic workflow to help you get started with Actions

name: JavaScript CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Upgrade npm
        run: npm install -g npm
      - name: npm install
        run: |
          cd ./javascript/xpath-helper
          npm ci
      
      - name: npm build
        run: |
          cd ./javascript/xpath-helper
          npm run build --if-present

      - name: npm lint
        run: |
          cd ./javascript/xpath-helper
          npm run lint

      - name: npm test
        run: |
          cd ./javascript/xpath-helper
          npm run coverage
      
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./javascript/xpath-helper/coverage/lcov.info
          flag-name: JavaScript Coverage
